models/Base.py
from .db import db
from sqlalchemy.sql import func

class Base(db.Model):
    __abstract__ = True
    id = db.Column('id', db.Integer, nullable = False, primary_key = True, autoincrement = True)
    deleted = db.Column('deleted', db.Integer, nullable=False, default = 0)
    date_add = db.Column('date_add', db.DateTime, nullable=False, default = func.now())
    date_upd = db.Column('date_upd', db.DateTime, nullable=False, default = func.now())

    def serialize(self):
        return {
            'id': self.id,
            'deleted': self.deleted,
            'date_add': None if self.date_add is None else self.date_add.isoformat(),
            'date_upd': None if self.date_upd is None else self.date_upd.isoformat(),
        }

models/__init__.py
import click
from flask import current_app, g

from .db import db
from . import auth,main,profile,party

def init_app (app):
    

    db.init_app(app)
    main.init_app(app,db)
    auth.init_app(app,db)
    profile.init_app(app,db)
    party.init_app(app,db)


    def get_db_session(config = None):

        if config is None:
            config = app.config
        
        if 'session' not in g:
            g.db_session = db

        return g.db_session


    def close_db_session(e=None):
        session = g.pop('db_session', None)

        if session is not None:
            session.close()

    app.teardown_appcontext(close_db_session)


    return app

models/db.py
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()

__init__.py
from .create_app import create_app

commands/__init__.py
from ..models.db import db
from . import resetDb, house

def init_app(app):

    resetDb.init_app(app,db)
    house.init_app(app,db)

models/main/__init__.py
from ..Base import Base

from .Image import Image


from flask.cli import with_appcontext


def init_app(app,db):
    pass

models/party/__init__.py
from .Party import Party
from .Deck import Deck
from .Card import Card

def init_app(app,db):
    pass

models/profile/__init__.py
from ..Base import Base
from ..db import db

from .Avatar import Avatar
from .Profile import Profile
from ..main import Image


from flask.cli import with_appcontext

import math, time, hashlib
from PIL import Image as PIL_Image

def setAvatarImage(user, image):
    filename = 'avatar_'+str(user.id)+'_'+str(math.floor(1000*time.time()))
    m = hashlib.md5()
    m.update(str(math.floor(1000*time.time())).encode('utf-8'))
    token = m.hexdigest()
    croped_image = image.crop((0,0,min(image.size),min(image.size)))
    
    file_descriptor, file_mime = Image.save( croped_image,filename, max_width=512,max_height=512)

    img = PIL_Image.open(file_descriptor)
    w,h = img.size

    # if exists, replace previous avatar
    oldAvatar = user.profile.avatar
    if oldAvatar is not None:
        oldAvatar.profile = None

    avatar = Avatar(
        file_descriptor = file_descriptor,
        file_mime = file_mime,
        token = token,
        profile = user.profile
    )

    db.session.add(avatar)
    db.session.commit()


def setAvatarImageFromUrlData(user, imageData):
    
    filename = 'avatar_'+str(user.id)+'_'+str(math.floor(1000*time.time()))
    m = hashlib.md5()
    m.update(str(math.floor(1000*time.time())).encode('utf-8'))
    token = m.hexdigest()
    file_descriptor, file_mime = Image.save_from_urlData( imageData,filename, max_width=512,max_height=512)

    img = PIL_Image.open(file_descriptor)
    w,h = img.size

    # if exists, replace previous avatar
    oldAvatar = user.profile.avatar
    if oldAvatar is not None:
        oldAvatar.profile = None

    avatar = Avatar(
        file_descriptor = file_descriptor,
        file_mime = file_mime,
        token = token,
        profile = user.profile
    )

    db.session.add(avatar)
    db.session.commit()

def init_app(app,db):
    pass

routes/__init__.py
from flask import current_app, g, jsonify, Blueprint, session
from .. import models
from . import auth, main, admin, profile, socketExamples, parties

def init_app(app):
    print('routes/__init__.py init_app(app)')

    '''
        Identify username
    '''
    @auth.bp.before_app_request
    @main.bp.before_app_request
    @admin.bp.before_app_request
    @admin.bp_api.before_app_request
    @profile.bp.before_app_request
    @profile.bp_api.before_app_request
    @socketExamples.bp.before_app_request
    @socketExamples.bp_api.before_app_request
    @parties.bp.before_app_request
    @parties.bp_api.before_app_request
    def load_logged_in_user():
        auth.load_logged_in_user()


    '''
        Register modules
    '''
    app.register_blueprint(main.bp)
    app.register_blueprint(auth.bp)
    app.register_blueprint(auth.bp_api)
    app.register_blueprint(admin.bp)
    app.register_blueprint(admin.bp_api)
    app.register_blueprint(profile.bp)
    app.register_blueprint(profile.bp_api)
    app.register_blueprint(socketExamples.bp)
    app.register_blueprint(socketExamples.bp_api)
    app.register_blueprint(parties.bp)
    app.register_blueprint(parties.bp_api)

    '''
        Error handlers
    '''
    app.register_error_handler(404, main.page_not_found)

    '''
        Special endpoints
    '''
    app.add_url_rule('/', endpoint='index')

    return app

routes/admin/__init__.py
import functools

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from .. import models

from . import main,users,groups

#from libgravatar import Gravatar

bp = Blueprint('admin', __name__, url_prefix='/admin')
bp_api = Blueprint('api/admin', __name__, url_prefix='/api/admin')

main.append(bp,bp_api)
users.append(bp,bp_api)
groups.append(bp,bp_api)

routes/admin/main.py
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for,jsonify, abort
from werkzeug.security import check_password_hash, generate_password_hash

from ... import models
from .. import auth

def append(bp,bp_api):

    @bp.route('/', methods=('GET',))
    @auth.login_required
    @auth.group_required('active')
    @auth.group_required('admin')
    @auth.notin_group_required('blocked')
    def main():
        return render_template('admin/main.html', me = g.me, groups = models.auth.Group.query.all())

routes/main/__init__.py
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from .. import models

from . import index

bp = Blueprint('main', __name__, url_prefix='/')

def page_not_found(e):
  return render_template('main/404.html'), 404

index.append(bp)

routes/parties/__init__.py
import functools

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from .. import models

from . import party

#from libgravatar import Gravatar

bp = Blueprint('parties', __name__, url_prefix='/parties')
bp_api = Blueprint('api/parties', __name__, url_prefix='/api/parties')

party.append(bp,bp_api)

routes/profile/__init__.py
import functools

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from .. import models

from . import profile, avatar

#from libgravatar import Gravatar

bp = Blueprint('profile', __name__, url_prefix='/profile')
bp_api = Blueprint('api/profile', __name__, url_prefix='/api/profile')

profile.append(bp,bp_api)
avatar.append(bp,bp_api)

routes/socketExamples/__init__.py
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for

from .. import models

from . import chat

bp = Blueprint('sockets', __name__, url_prefix='/')
bp_api = Blueprint('api/sockets', __name__, url_prefix='/api/sockets')

chat.append(bp,bp_api)

socketio/__init__.py
from flask_socketio import SocketIO

from .chat import Chat
from .party import Party

def init_app(app):

    socketio = SocketIO(app)
    
    socketio.on_namespace(Chat('/chat'))
    socketio.on_namespace(Party('/party'))

templates/layouts/canvas_layout.html
{% from 'macros/navbar.html' import navbar with context %}
<!doctype html>
<html lang="en">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>APP_NAME</title>
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}"> {% block localCss %}{% endblock %}
</head>

<body>
    
    <canvas id='cv1' class="w-100 h-100"></canvas>

    {% block globalJs %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script>
        (function () {
            const canvas = document.getElementById('cv1');
            if (canvas.requestFullscreen) {
                canvas.requestFullscreen();
            }
        })()
    </script>
    <script src="{{ url_for('static', filename='jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/bootstrap.min.js') }}"></script>
    {% endblock %} {% block localJs %}{% endblock %}
</body>

</html>

templates/layouts/layout.html
{% from 'macros/navbar.html' import navbar with context %}
<!doctype html>
<html lang="en">
    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>APP_NAME</title>
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
        {% block localCss %}{% endblock %}
    </head>
    <body>
        {% block navbar -%}
        {{ navbar() }}
        {%- endblock %}

        <main role="main" class="container-fluid" style="margin-top: 64px;">
            <div class ="row">
                <div class="col-md-12">
                    {% for message in get_flashed_messages() %}
                    <div class=flash>{{ message }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class ="row">
                <div class ="col-md-12">
                    {% block body %}{% endblock %}
                </div>
            </div>
        </main>
        
        {% block globalJs %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{{ url_for('static', filename='jquery-3.3.1.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/popper.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/bootstrap.min.js') }}"></script>
        {% endblock %}
        {% block localJs %}{% endblock %}
    </body>
</html>

templates/macros/navbar.html
{% macro navbar() -%}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">APP_NAME</a>

    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarCollapse"
        aria-controls="navbarCollapse"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if not session.logged_in %}
                <li class="nav-item active">
                    <a href="{{ url_for('auth.login') }}" class ="nav-link">Log in</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('auth.register') }}" class ="nav-link">Sign up</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a href="{{ url_for('main.index') }}" class ="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('sockets.chat') }}" class ="nav-link">Chat</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('parties.parties', token = 'aoeu') }}" class ="nav-link">Party</a>
                </li>
                {% if not g.me.belongsTo('register') %}
                    {% if g.me.profile %}
                        <li class="nav-item">
                            <a href="{{ url_for('profile.own_profile',) }}" class ="nav-link">My profile</a>
                        </li>
                    {% endif %}
                    {% if g.me.belongsTo('admin') %}
                        <li class="nav-item">
                            <a href="{{ url_for('admin.main') }}" class = "nav-link">Administration</a>
                        </li>        
                    {% endif %}
                {% endif %}
                <li class="nav-item">
                    <a href="{{ url_for('auth.logout') }}" class = "nav-link">Log out</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{%- endmacro %}

templates/main/home.html
{% extends "layouts/layout.html" %}
{% block body %}
    <div class ="row" style="padding-top: 100px;">
        <div class="col-12 text-center">

            <h1>Home</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi aliquam, massa vitae tempus laoreet, ligula velit vehicula nulla, quis consectetur neque tellus non arcu. Fusce magna lacus, consectetur a dignissim vitae, fringilla ac ligula. Maecenas pulvinar est blandit mauris vulputate fermentum. Quisque posuere sit amet ante vitae tempor. Vivamus finibus condimentum ultrices. Sed et ligula elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque suscipit sapien enim, nec bibendum ante ultricies vel.</p>
            <p>Donec facilisis, magna in sollicitudin accumsan, risus risus mollis urna, vitae vestibulum dolor nisl nec odio. Pellentesque iaculis elit ut nunc congue, nec sodales purus accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In sit amet arcu suscipit magna dapibus imperdiet. Donec ut congue tortor. Donec eleifend sem sed massa mollis eleifend. Aenean dictum in massa ac rutrum. Pellentesque congue congue sapien, nec vehicula est sagittis et. Aliquam erat volutpat. Mauris eleifend tellus sed nisi bibendum pharetra. Nunc gravida nisl eu tellus lacinia, quis fringilla ante maximus. Mauris congue ut justo quis gravida.</p>
            <p>Vestibulum lobortis felis ut eros feugiat vestibulum. Phasellus placerat sapien ac neque congue rhoncus. Cras eget felis mauris. Morbi ipsum turpis, tincidunt ut libero a, convallis cursus leo. Phasellus mollis libero non velit congue, at aliquet ligula iaculis. Quisque volutpat magna egestas, auctor neque ac, varius magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus vel odio ante. Mauris condimentum tellus ante, sit amet vehicula sapien egestas porttitor. Maecenas malesuada enim id tempus dignissim. Aliquam sit amet tempor quam. Pellentesque nec lacus ligula. Quisque nibh risus, sagittis ut hendrerit at, fermentum vel magna. Suspendisse semper erat a arcu venenatis, ut consequat massa consequat. Donec sodales magna sed nisi tincidunt tempus.</p>
        </div>
    </div>
{% endblock %}

templates/main/welcome.html
{% extends "layouts/layout.html" %}
{% block body %}
    <div class ="row" style="padding-top: 100px;">
        <div class="col-12 text-center">

            <h1>Welcome {{me.profile.first_name}}</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi aliquam, massa vitae tempus laoreet, ligula velit vehicula nulla, quis consectetur neque tellus non arcu. Fusce magna lacus, consectetur a dignissim vitae, fringilla ac ligula. Maecenas pulvinar est blandit mauris vulputate fermentum. Quisque posuere sit amet ante vitae tempor. Vivamus finibus condimentum ultrices. Sed et ligula elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque suscipit sapien enim, nec bibendum ante ultricies vel.</p>
            <p>Donec facilisis, magna in sollicitudin accumsan, risus risus mollis urna, vitae vestibulum dolor nisl nec odio. Pellentesque iaculis elit ut nunc congue, nec sodales purus accumsan. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In sit amet arcu suscipit magna dapibus imperdiet. Donec ut congue tortor. Donec eleifend sem sed massa mollis eleifend. Aenean dictum in massa ac rutrum. Pellentesque congue congue sapien, nec vehicula est sagittis et. Aliquam erat volutpat. Mauris eleifend tellus sed nisi bibendum pharetra. Nunc gravida nisl eu tellus lacinia, quis fringilla ante maximus. Mauris congue ut justo quis gravida.</p>
            <p>Vestibulum lobortis felis ut eros feugiat vestibulum. Phasellus placerat sapien ac neque congue rhoncus. Cras eget felis mauris. Morbi ipsum turpis, tincidunt ut libero a, convallis cursus leo. Phasellus mollis libero non velit congue, at aliquet ligula iaculis. Quisque volutpat magna egestas, auctor neque ac, varius magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus vel odio ante. Mauris condimentum tellus ante, sit amet vehicula sapien egestas porttitor. Maecenas malesuada enim id tempus dignissim. Aliquam sit amet tempor quam. Pellentesque nec lacus ligula. Quisque nibh risus, sagittis ut hendrerit at, fermentum vel magna. Suspendisse semper erat a arcu venenatis, ut consequat massa consequat. Donec sodales magna sed nisi tincidunt tempus.</p>
        </div>
    </div>
{% endblock %}

templates/party/create.html
{% extends "layouts/layout.html" %} {% block body %}

<div class="row">
	
	<div class="col-12 col-lg-6">
		<div class="text-center pt-4 pb-4" style="max-width: 420px; margin: auto;">
			<h5 class="h3 mb-3 font-weight-normal">New Party</h5>
			<p>Create your own party or <a href="{{ url_for('parties.parties') }}">join to a created one</a></p>
		</div>
		<form class="form-create-party" style="max-width: 420px; margin: auto;" method="POST">

			<div class="form-row">
				<div class="form-group col-12">
					<label for="inputParty_name">Party Name</label>
					<input name="party_name" id="inputParty_name" class="form-control" placeholder="{{ g.me.profile.first_name }}'s party" required=""
					    type="text">
				</div>
			</div>

			<div class="form-row">
				<div class="form-group col-12">
					<button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
				</div>
			</div>

		</form>

	</div>
</div>
{% endblock %} {% block localCss %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous"> {% endblock %} {% block localJs %}
<script src="{{ url_for('static',filename='js/parties/create.page.js') }}"></script>
{% endblock %}

templates/party/party.html
{% extends "layouts/canvas_layout.html" %}
{% block localCss %}
<link rel="stylesheet" href="{{ url_for( 'static',filename='css/party.page.css' ) }}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
{% endblock %}

{% block localJs %}
<script type="text/javascript" src="{{ url_for('static',filename='js/socket.io.min.js') }}"></script>
<script>
    const g = {
        me: {
            id: {{ g.me.id }},
        },
        party: {
            token: "{{ token }}",
        },
    }
</script>
<script src="{{ url_for('static',filename='three.min.js') }}"></script>
<script src="{{ url_for('static',filename='orbitControls.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/cameraModel.class.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/lightManager.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/sceneManager.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/drawings.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/drawer.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/touchManager.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/userManager.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/region.class.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/card.class.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/cardManager.class.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/table.class.js') }}"></script>
<script src="{{ url_for('static',filename='js/parties/started/party.page.js') }}"></script>
{% endblock %}

templates/profile/own_profile.html
{% extends "layouts/layout.html" %}
{% block body %}
    <div class="py-5" style="max-width: 420px; margin: auto;">
        
        <div class="card border-secondary" id="selfie-card" style="max-width: 420px; margin: auto;padding: 16px;">
            <video autoplay class="card-img-top border bg-secondary d-none" alt="Card image cap"></video>
            <canvas class="card-img-top border d-none" alt="Card image cap"></canvas>
            <img class="card-img-top border" id='profile-img' src="" alt="Card image cap">

            <div class="card-body text-center">
                <div class="btn-group w-100 pb-2">
                    <a href="#" id="takeSelfie-btn" class="btn btn-primary w-100">
                        <i class="fa fa-camera"></i>
                        <span>Take a Selfie!</span>
                    </a>
                </div>
                <div class="btn-group w-100 pb-2 d-none">
                    <a href="#" id="reTakeSelfie-btn" class="btn btn-outline-danger w-100">
                        <i class="fa fa-sync"></i>
                        <span>Repeat</span>
                    </a>
                    <a href="#" id="removeSelfie-btn" class="btn btn-outline-danger">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="text-center mt-4">
            ... or if you prefer just
            <a href="#" id="uploadPhoto-btn" class="btn btn-link">Upload Photo</a>
        </div>
        <div class="mt-4 w-100 pb-2 d-none">
            <a href="#" id="updateSelfie-btn" class="btn btn-primary w-100">
                <i class="fa fa-upload"></i>
                <span>Update!</span>
            </a>
        </div>
        <div  class ="py-5 text-center">
            <h4 id="complete-name">First Name + Last Name</h4>
        </div>
    </div>
{% endblock %}
{% block localJs %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
<script src="{{ url_for('static',filename='js/own_profile.page.js') }}"></script>

{% endblock %}

templates/profile/profile.html
{% extends "layouts/layout.html" %}
{% block body %}
    <div class="py-5" style="max-width: 420px; margin: auto;">

        <div class="card border-secondary" id="selfie-card" style="max-width: 420px; margin: auto;padding: 16px;">
            <img class="card-img-top border" id='profile-img' src="" alt="Card image cap">
        </div>
        <div  class ="py-5 text-center">
            <h4 id="complete-name">First Name + Last Name</h4>
        </div>
    </div>
{% endblock %}
{% block localJs %}
<script>
    $(document).ready(function (event) {
        
        $.ajax({
            url: "/api/profile/{{user.id}}",
            type: 'GET',
            contentType: "application/json; charset=utf-8",
            async: true,
            success: function (data) {
                console.log(data);
                document.getElementById('profile-img').src = data.profile.avatar
                document.getElementById('complete-name').innerHTML = data.profile.first_name + ' ' + data.profile.last_name

                
            },
            error: function (data) {
                console.error(data)
            }
        });            
    })
</script>
{% endblock %}